# fly.toml app configuration file generated for netbin on 2024-10-31T00:33:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'netbin'
primary_region = 'bog'

[build]

[[services]]
  internal_port = 1883
  protcol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 1883
    handlers = [ ]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
