# fly.toml app configuration file generated for brokerservice on 2024-10-31T10:55:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brokerservice'
primary_region = 'bog'

[build]

[[services.ports]]
  handlers = [ ]
  port = "1883"

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source="mosquitto_data"
  destination="/mosquitto/data"

